---
title: "705-hmwrk-5"
author: "Graham"
date: "October 21, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#a

```{r}

data <- read.table("data.dat",header = T)

X <- cbind(1,data$x1,data$x2,data$x3,data$x4)
y <- data$y


beta_hat <- solve(t(X)%*%X)%*%t(X)%*%y
y_bar <- mean(y)
n <- nrow(X)
k <- 4

SSR <- t(beta_hat)%*%t(X)%*%y - n*y_bar^2
SSE <- t(y)%*%y- t(beta_hat)%*%t(X)%*%y


F_stat <- (SSR/k)/(SSE/(n-k-1))

pf(F_stat,df1=k,df2=n-k-1,lower.tail = F)


```


#b

Here we use the reduced model approach, where we fit the model 

$$y = \beta_0^* + \beta_2^*x_2 + \beta_4^*x_4 + \epsilon$$





```{r}


X <- cbind(1,data$x2,data$x4)

y <- data$y


beta_hat <- solve(t(X)%*%X)%*%t(X)%*%y
y_bar <- mean(y)
n <- nrow(X)
k <- 2

SSR_reduced <- t(beta_hat)%*%t(X)%*%y - n*y_bar^2

SSR-SSR_reduced

F_stat <- ((SSR-SSR_reduced)/2)/(SSE/(n-4-1))

pf(F_stat,df1=2,df2=n-k-1,lower.tail = F)

```

We cannot reject the null hypothesis at the $.5$ level. 



```{r}


s_squared <- SSE/(n-4-1)
g <- t(X)%*%X

X <- cbind(1,data$x1,data$x2,data$x3,data$x4)
y <- data$y


beta_hat <- solve(t(X)%*%X)%*%t(X)%*%y

cov_beta <- as.numeric(s_squared)*solve(t(X)%*%X)

t_tests <- beta_hat/sqrt(diag(cov_beta))

p_vals <- c()
for (t in t_tests){
  p_vals <- c(p_vals,2*pt(abs(t),lower.tail = F,df=n-4-1))
}

```

Which, if we compare to the bonferonni correction of $.5/4$ we can reject $H_0$ for $\beta_2$ and $\beta_4$.



# d
We can use the contrast matrix approach where we let 

$$C= \begin{pmatrix} 
0 & 1 & -1 & 0 & 0 \\
0  & 0 & 1 & -12 & 0\\
0  & 0 & 0 & 1 & -1
\end{pmatrix}$$


We can compute the residual sum of squares row by row in 


```{r}

#H_0

C_total <- matrix(c(0,1,-1,0,0,0,0,1,-12,0,0,0,0,1,-1),byrow = T,ncol=5)
C <- C_total
beta_c <- beta_hat - solve(t(X)%*%X)%*%t(C)%*%solve(C%*%solve(t(X)%*%X)%*%t(C))%*%C%*%beta_hat

SSbetac_c <- t(beta_c)%*%t(X)%*%y -  n*y_bar^2

SSH <- SSR - SSbetac_c

pf((SSH/3)/(SSE/(n-4-1)),lower.tail = F,df1=3,df2=n-4-1)


#H_01
C_total <- matrix(c(0,1,-1,0,0,0,0,1,-12,0,0,0,0,1,-1),byrow = T,ncol=5)
C <- matrix(C_total[1,],nrow=1)
beta_c <- beta_hat - solve(t(X)%*%X)%*%t(C)%*%solve(C%*%solve(t(X)%*%X)%*%t(C))%*%C%*%beta_hat

SSbetac_c <- t(beta_c)%*%t(X)%*%y -  n*y_bar^2

SSH <- SSR - SSbetac_c

pf(SSH/(SSE/(n-4-1)),lower.tail = F,df1=1,df2=n-4-1)


#H_02
C_total <- matrix(c(0,1,-1,0,0,0,0,1,-12,0,0,0,0,1,-1),byrow = T,ncol=5)
C <- matrix(C_total[2,],nrow=1)
beta_c <- beta_hat - solve(t(X)%*%X)%*%t(C)%*%solve(C%*%solve(t(X)%*%X)%*%t(C))%*%C%*%beta_hat

SSbetac_c <- t(beta_c)%*%t(X)%*%y -  n*y_bar^2

SSH <- SSR - SSbetac_c

pf(SSH/(SSE/(n-4-1)),lower.tail = F,df1=1,df2=n-4-1)

#H_03
C_total <- matrix(c(0,1,-1,0,0,0,0,1,-12,0,0,0,0,1,-1),byrow = T,ncol=5)
C <- matrix(C_total[3,],nrow=1)
beta_c <- beta_hat - solve(t(X)%*%X)%*%t(C)%*%solve(C%*%solve(t(X)%*%X)%*%t(C))%*%C%*%beta_hat

SSbetac_c <- t(beta_c)%*%t(X)%*%y -  n*y_bar^2

SSH <- SSR - SSbetac_c

pf(SSH/(SSE/(n-4-1)),lower.tail = F,df1=1,df2=n-4-1)

#H_04

C_total <- matrix(c(0,1,-1,0,0,0,0,1,-12,0,0,0,0,1,-1),byrow = T,ncol=5)
C <- matrix(C_total[c(1,3),],nrow=2)
beta_c <- beta_hat - solve(t(X)%*%X)%*%t(C)%*%solve(C%*%solve(t(X)%*%X)%*%t(C))%*%C%*%beta_hat

SSbetac_c <- t(beta_c)%*%t(X)%*%y -  n*y_bar^2

SSH <- SSR - SSbetac_c

pf((SSH/2)/(SSE/(n-4-1)),lower.tail = F,df1=2,df2=n-4-1)


```



```{r}

X <- cbind(1,data$x1,data$x2,data$x3,data$x4)
y <- data$y


beta_hat <- solve(t(X)%*%X)%*%t(X)%*%y
SSE <- t(y)%*%y- t(beta_hat)%*%t(X)%*%y

s_squared <- SSE/(n-4-1)

cov_beta <- as.numeric(s_squared)*solve(t(X)%*%X)

beta_hat_upper_95 <- beta_hat + 2.0518*sqrt(diag(cov_beta))
beta_hat_lower_95 <- beta_hat - 2.0518*sqrt(diag(cov_beta))


beta_hat_upper_975 <- beta_hat + 2.6763*sqrt(diag(cov_beta))
beta_hat_lower_975 <- beta_hat - 2.6763*sqrt(diag(cov_beta))


```



